version: '3'

services:
  bms-auth:
    container_name: bms-auth
    build:
      context: ./../bms-auth
      dockerfile: Dockerfile
    volumes:
      - ./../bms-auth:/app
    ports:
      - 5001:5001
    env_file:
      - ./../bms-auth/.env
    depends_on:
      - bms-db
      - bms-rabbitmq

  bms-org:
    container_name: bms-org
    build:
      context: ./../bms-org
      dockerfile: Dockerfile
    ports:
      - 5002:5002
    volumes:
      - ./../bms-org:/app
    env_file:
      - ./../bms-org/.env
    depends_on:
      - bms-db
      - bms-rabbitmq

  bms-db:
    container_name: bms-db
    image: postgres
    restart: always
    volumes:
      - pgData:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: bms-admin
      POSTGRES_PASSWORD: bms-admin
      POSTGRES_DB: BMS
    ports:
      - "5432:5432"

  bms-rabbitmq:
    container_name: bms-rabbitmq
    image: rabbitmq:management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmqData:/var/lib/rabbitmq


  bms-core:
    container_name: bms-core
    build: .
    volumes:
      - ./nginx.conf:/etc/nginx/nginx/conf
    ports:
      - 80:80
    depends_on:
      - bms-auth
      - bms-org

volumes:
  pgData:
  rabbitmqData:
