version: '3'
services:
  bms-auth:
    container_name: bms-auth
    build: 
      context: ./../bms-auth
      dockerfile: Dockerfile
    volumes:
      - ./../bms-auth:/app
    ports:
      - 5001:5001
    environment:
      - PORT=5001
    
  bms-core:
    container_name: bms-core
    build: .
    volumes:
      - ./nginx.conf:/etc/nginx/nginx/conf
    ports:
      - 80:80
    depends_on:
      - bms-auth
